window.DEMO_PLACES = [
  {
    "id": "mc00",
    "name": "địa phận bản lác 2",
    "type": "service",
    "lat": 20.6517741481822,
    "lng": 105.062365465313,
    "summary": "Diem trai nghiem: địa phận bản lác 2",
    "cultural_notes": "Ton trong khong gian cong dong va xin phep truoc khi ghi hinh.",
    "record_permission": "ask",
    "sensitivity_level": "public",
    "audio_url": "",
    "pano360_url": "",
    "images": [],
    "duration_minutes": 60,
    "price_range": "",
    "contact_zalo": "",
    "contact_phone": "",
    "source_note": "Du lieu nhap tu Google Sheet (dữ liệu điểm - mau_google_sheet_places_template.csv)."
  },
  {
    "id": "mc01",
    "name": "hoa ban lalastay",
    "type": "service",
    "lat": 20.649013833365,
    "lng": 105.068346121137,
    "summary": "lưu trú nhà dân",
    "cultural_notes": "Giữ yên tĩnh sau 22h; tôn trọng không gian sinh hoạt chung",
    "record_permission": "ask",
    "sensitivity_level": "public",
    "audio_url": "",
    "pano360_url": "",
    "images": [],
    "duration_minutes": 60,
    "price_range": "300k-800k",
    "contact_zalo": "",
    "contact_phone": "0329000644",
    "source_note": "Du lieu nhap tu Google Sheet (dữ liệu điểm - mau_google_sheet_places_template.csv)."
  },
  {
    "id": "mc02",
    "name": "mai châu farmstay",
    "type": "service",
    "lat": 20.6487209050322,
    "lng": 105.068971173523,
    "summary": "lưu trú nhà dân",
    "cultural_notes": "Giữ yên tĩnh sau 22h; tôn trọng không gian sinh hoạt chung",
    "record_permission": "ask",
    "sensitivity_level": "public",
    "audio_url": "",
    "pano360_url": "",
    "images": [],
    "duration_minutes": 60,
    "price_range": "500k-1800k",
    "contact_zalo": "http://maichaufarmstay.com/",
    "contact_phone": "0978586555",
    "source_note": "Du lieu nhap tu Google Sheet (dữ liệu điểm - mau_google_sheet_places_template.csv)."
  },
  {
    "id": "mc03",
    "name": "mai châu village view homestay",
    "type": "service",
    "lat": 20.6623108103279,
    "lng": 105.064455209491,
    "summary": "lưu trú nhà dân",
    "cultural_notes": "Giữ yên tĩnh sau 22h; tôn trọng không gian sinh hoạt chung",
    "record_permission": "ask",
    "sensitivity_level": "public",
    "audio_url": "",
    "pano360_url": "",
    "images": [],
    "duration_minutes": 60,
    "price_range": "300k-500k",
    "contact_zalo": "",
    "contact_phone": "0984905796",
    "source_note": "Du lieu nhap tu Google Sheet (dữ liệu điểm - mau_google_sheet_places_template.csv)."
  },
  {
    "id": "pc01",
    "name": "mông space",
    "type": "service",
    "lat": 20.7503095755877,
    "lng": 104.906796665878,
    "summary": "điểm du lịch trải nghiệm văn hóa dân tộc hmong thu nhỏ",
    "cultural_notes": "Ton trong khong gian cong dong va xin phep truoc khi ghi hinh.",
    "record_permission": "allowed",
    "sensitivity_level": "public",
    "audio_url": "",
    "pano360_url": "",
    "images": [],
    "duration_minutes": 60,
    "price_range": "",
    "contact_zalo": "",
    "contact_phone": "0369947995",
    "source_note": "Du lieu nhap tu Google Sheet (dữ liệu điểm - mau_google_sheet_places_template.csv)."
  },
  {
    "id": "pc02",
    "name": "mông lềnh space",
    "type": "service",
    "lat": 20.7464499105634,
    "lng": 104.874994117938,
    "summary": "không gian văn hóa mông lềnh trải nghiệm dệt đồ thổ cẩm",
    "cultural_notes": "Ton trong khong gian cong dong va xin phep truoc khi ghi hinh.",
    "record_permission": "ask",
    "sensitivity_level": "public",
    "audio_url": "",
    "pano360_url": "",
    "images": [],
    "duration_minutes": 60,
    "price_range": "",
    "contact_zalo": "",
    "contact_phone": "0355466801",
    "source_note": "Du lieu nhap tu Google Sheet (dữ liệu điểm - mau_google_sheet_places_template.csv)."
  },
  {
    "id": "pc03",
    "name": "homestay y múa",
    "type": "service",
    "lat": 20.7483880083249,
    "lng": 104.883223290457,
    "summary": "lưu trú nhà dân",
    "cultural_notes": "Giữ yên tĩnh sau 22h; tôn trọng không gian sinh hoạt chung",
    "record_permission": "ask",
    "sensitivity_level": "public",
    "audio_url": "",
    "pano360_url": "",
    "images": [],
    "duration_minutes": 60,
    "price_range": "520k-800k",
    "contact_zalo": "http://www.facebook.com/YMua.homestay/",
    "contact_phone": "0355466801",
    "source_note": "Du lieu nhap tu Google Sheet (dữ liệu điểm - mau_google_sheet_places_template.csv)."
  },
  {
    "id": "pc04",
    "name": "highland homestay",
    "type": "service",
    "lat": 20.7382768547763,
    "lng": 104.885965152384,
    "summary": "lưu trú nhà dân",
    "cultural_notes": "Giữ yên tĩnh sau 22h; tôn trọng không gian sinh hoạt chung",
    "record_permission": "ask",
    "sensitivity_level": "public",
    "audio_url": "",
    "pano360_url": "",
    "images": [],
    "duration_minutes": 60,
    "price_range": "400k-500k",
    "contact_zalo": "",
    "contact_phone": "0974714199",
    "source_note": "Du lieu nhap tu Google Sheet (dữ liệu điểm - mau_google_sheet_places_template.csv)."
  },
  {
    "id": "pc05",
    "name": "a dơ homestay",
    "type": "service",
    "lat": 20.7484430347202,
    "lng": 104.885388380314,
    "summary": "lưu trú nhà dân",
    "cultural_notes": "Giữ yên tĩnh sau 22h; tôn trọng không gian sinh hoạt chung",
    "record_permission": "ask",
    "sensitivity_level": "public",
    "audio_url": "",
    "pano360_url": "",
    "images": [],
    "duration_minutes": 60,
    "price_range": "",
    "contact_zalo": "",
    "contact_phone": "0366376576",
    "source_note": "Du lieu nhap tu Google Sheet (dữ liệu điểm - mau_google_sheet_places_template.csv)."
  },
  {
    "id": "pc06",
    "name": "homestay vườn đào hang kia",
    "type": "service",
    "lat": 20.7458181783637,
    "lng": 104.88133368379,
    "summary": "lưu trú nhà dân",
    "cultural_notes": "Giữ yên tĩnh sau 22h; tôn trọng không gian sinh hoạt chung",
    "record_permission": "ask",
    "sensitivity_level": "public",
    "audio_url": "",
    "pano360_url": "",
    "images": [],
    "duration_minutes": 60,
    "price_range": "",
    "contact_zalo": "",
    "contact_phone": "0969993698",
    "source_note": "Du lieu nhap tu Google Sheet (dữ liệu điểm - mau_google_sheet_places_template.csv)."
  },
  {
    "id": "pc07",
    "name": "homestay a thống",
    "type": "service",
    "lat": 20.7459856084086,
    "lng": 104.881996178973,
    "summary": "lưu trú nhà dân",
    "cultural_notes": "Giữ yên tĩnh sau 22h; tôn trọng không gian sinh hoạt chung",
    "record_permission": "ask",
    "sensitivity_level": "public",
    "audio_url": "",
    "pano360_url": "",
    "images": [],
    "duration_minutes": 60,
    "price_range": "300k-600k",
    "contact_zalo": "",
    "contact_phone": "0356662899",
    "source_note": "Du lieu nhap tu Google Sheet (dữ liệu điểm - mau_google_sheet_places_template.csv)."
  }
];

window.DEMO_ROUTE_OPTIONS = [
  {
    id: 'rt-pa-co-cloud-halfday',
    title: 'Săn mây Pà Cò',
    duration: 'half_day',
    groupMin: 2,
    groupMax: 6,
    budgetMin: 0,
    budgetMax: 500000,
    transportModes: ['self_drive'],
    focusPlaceId: 'pc06',
    placeIds: ['pc06', 'pc03'],
    description: 'Lộ trình ngắn phù hợp nhóm nhỏ muốn săn mây và check-in cảnh quan.',
    notes: ['Hà Nội', 'Hang Kia săn mây', 'Đồi chè Pà Cò', 'Bản Thung Mài', 'Thác Suối Tú', 'Xã Pà Cò'],
    homestay: 'Homestay Y Múa'
  },
  {
    id: 'rt-van-hoa-mong-oneday',
    title: 'Văn hóa Mông',
    duration: 'one_day',
    groupMin: 2,
    groupMax: 10,
    budgetMin: 500000,
    budgetMax: 900000,
    transportModes: ['coach'],
    focusPlaceId: 'pc02',
    placeIds: ['pc02', 'pc01'],
    description: 'Tham quan chợ, làng nghề và không gian văn hóa cộng đồng trong 1 ngày.',
    notes: ['Hà Nội', 'Chợ Pà Cò', 'Vườn hoa Hoa Phượng', 'Dệt thổ cẩm', 'Đồi Mai', 'Xã Pà Cò'],
    homestay: 'Homestay A La'
  },
  {
    id: 'rt-trekking-rung-oneday',
    title: 'Trekking rừng',
    duration: 'one_day',
    groupMin: 2,
    groupMax: 6,
    budgetMin: 500000,
    budgetMax: 900000,
    transportModes: ['self_drive'],
    focusPlaceId: 'pc06',
    placeIds: ['pc06', 'pc07'],
    description: 'Lộ trình trekking thiên nhiên cho nhóm nhỏ yêu khám phá sinh thái.',
    notes: ['Hà Nội', 'Hang Nhím', 'Suối Răm', 'Thác Suối Tú', 'Xã Pà Cò'],
    homestay: 'Highland Homestay'
  },
  {
    id: 'rt-checkin-pa-co',
    title: 'Checkin Pà Cò',
    duration: 'one_day',
    groupMin: 2,
    groupMax: 8,
    budgetMin: 500000,
    budgetMax: 900000,
    transportModes: ['self_drive'],
    focusPlaceId: 'pc03',
    placeIds: ['pc03', 'pc01'],
    description: 'Tour chụp ảnh phong cảnh với các điểm check-in nổi bật trong ngày.',
    notes: ['Hà Nội', 'Đồi chè Pà Cò', 'Ruộng bậc thang', 'Viewpoint', 'Chợ Pà Cò', 'Xã Pà Cò'],
    homestay: 'Homestay Y Múa'
  },
  {
    id: 'rt-am-thuc-dia-phuong',
    title: 'Ẩm thực địa phương',
    duration: 'one_day',
    groupMin: 2,
    groupMax: 10,
    budgetMin: 500000,
    budgetMax: 900000,
    transportModes: ['self_drive', 'coach'],
    focusPlaceId: 'pc01',
    placeIds: ['pc01', 'pc02'],
    description: 'Khám phá ẩm thực Mông kết hợp trải nghiệm nghề và không gian bản địa.',
    notes: ['Hà Nội', 'Chợ Pà Cò', 'Nhà dân', 'Dệt thổ cẩm', 'Ẩm thực Mông', 'Xã Pà Cò'],
    homestay: 'Homestay A Páo'
  },
  {
    id: 'rt-trai-nghiem-pa-co-2n1d',
    title: 'Trải nghiệm Pà Cò',
    duration: 'two_days',
    groupMin: 4,
    groupMax: 10,
    budgetMin: 900000,
    budgetMax: 1500000,
    transportModes: ['limousine'],
    focusPlaceId: 'pc05',
    placeIds: ['pc05', 'pc02', 'pc06'],
    description: 'Tour 2N1Đ kết hợp văn hoá, nghề thủ công và cảnh quan đặc trưng Pà Cò.',
    notes: ['Hà Nội', 'Chợ Pà Cò', 'Vườn hoa Hoa Phượng', 'Dệt thổ cẩm', 'Hang Kia săn mây', 'Đồi chè Pà Cò', 'Xã Pà Cò'],
    homestay: 'A Dơ Homestay'
  },
  {
    id: 'rt-trekking-suoi-2n1d',
    title: 'Trekking suối',
    duration: 'two_days',
    groupMin: 2,
    groupMax: 6,
    budgetMin: 900000,
    budgetMax: 1500000,
    transportModes: ['self_drive'],
    focusPlaceId: 'pc06',
    placeIds: ['pc06', 'pc07'],
    description: 'Lộ trình 2N1Đ thiên về trekking suối và trải nghiệm sinh thái.',
    notes: ['Hà Nội', 'Suối Răm', 'Thác Suối Tú', 'Xám Pà Nưa', 'Thác Suối Tú', 'Xã Pà Cò'],
    homestay: 'Homestay Vườn Đào Hang Kia'
  },
  {
    id: 'rt-san-may-hang-kia',
    title: 'Săn mây Hang Kia',
    duration: 'one_day',
    groupMin: 2,
    groupMax: 6,
    budgetMin: 500000,
    budgetMax: 900000,
    transportModes: ['self_drive'],
    focusPlaceId: 'pc06',
    placeIds: ['pc06', 'pc07'],
    description: 'Tour săn mây 1 ngày tại khu vực Hang Kia - Pà Cò.',
    notes: ['Hà Nội', 'Hang Kia săn mây', 'Bản Hang', 'Suối Răm', 'Xã Pà Cò'],
    homestay: 'Homestay Hang Kia'
  },
  {
    id: 'rt-tour-anh-pa-co',
    title: 'Tour ảnh Pà Cò',
    duration: 'half_day',
    groupMin: 2,
    groupMax: 8,
    budgetMin: 0,
    budgetMax: 500000,
    transportModes: ['self_drive'],
    focusPlaceId: 'pc03',
    placeIds: ['pc03', 'pc01'],
    description: 'Lộ trình nửa ngày dành cho nhóm chụp ảnh cảnh quan và văn hóa địa phương.',
    notes: ['Hà Nội', 'Hang Láng', 'Ruộng bậc thang', 'Đồi chè', 'Hang Láng', 'Xã Pà Cò']
  },
  {
    id: 'rt-kham-pha-pa-co-3n2d',
    title: 'Khám phá Pà Cò',
    duration: 'three_days',
    groupMin: 4,
    groupMax: 10,
    budgetMin: 1500000,
    budgetMax: 3000000,
    transportModes: ['limousine'],
    focusPlaceId: 'pc07',
    placeIds: ['pc07', 'pc02', 'pc06', 'pc01'],
    description: 'Tour 3N2Đ chuyên sâu khám phá văn hóa, cảnh quan và sinh hoạt cộng đồng.',
    notes: ['Hà Nội', 'Chợ Pà Cò', 'Vườn hoa Hoa Phượng', 'Hang Chiều', 'Chợ đêm Pà Cò', 'Cột cờ Mai Châu', 'Hang Nhím', 'Xã Pà Cò'],
    homestay: 'Homestay A Thống'
  }
];
